import { z } from 'zod';

const numeric = z.coerce.number();
const nullableNumeric = z.union([numeric, z.null()]);
const status = z.enum([
  'outperforming',
  'healthy',
  'watch',
  'risk',
  'recovering',
  'slowing',
  'volatile',
  'new',
  'exited',
]);
const meta = z.object({
  period: z.string(),
  comparison: z.enum(['previous-month', 'previous-year', 'none']),
  as_of: z.string().nullable(),
  is_final: z.boolean(),
  data_mode: z.enum(['demo', 'postgres']),
  currency: z.string(),
  scope_label: z.string(),
  generated_at: z.string(),
  source: z.string(),
});
const performanceRow = z.object({
  id: z.string(),
  label: z.string(),
  context: z.string(),
  entity_type: z.string(),
  sales: numeric,
  units: numeric,
  receipts: numeric,
  target: nullableNumeric.optional(),
  target_pct: nullableNumeric.optional(),
  previous_year_sales: nullableNumeric.optional(),
  previous_month_sales: nullableNumeric.optional(),
  recent_average_sales: nullableNumeric.optional(),
  yoy_pct: nullableNumeric.optional(),
  mom_pct: nullableNumeric.optional(),
  recent_pct: nullableNumeric.optional(),
  average_receipt: nullableNumeric.optional(),
  units_per_receipt: nullableNumeric.optional(),
  value_per_unit: nullableNumeric.optional(),
  bon2acc_pct: nullableNumeric.optional(),
  focus_pct: nullableNumeric.optional(),
  return_rate_pct: nullableNumeric.optional(),
  working_days: nullableNumeric.optional(),
  consistency_pct: nullableNumeric.optional(),
  performance_score: numeric,
  status,
  primary_driver: z.string(),
  primary_driver_impact: numeric,
  driver_basis: z.string(),
});
const productRow = z.object({
  id: z.string(),
  label: z.string(),
  brand: z.string(),
  category: z.string(),
  sales: numeric,
  previous_year_sales: nullableNumeric.optional(),
  recent_average_sales: nullableNumeric.optional(),
  yoy_pct: nullableNumeric.optional(),
  recent_pct: nullableNumeric.optional(),
  units: numeric,
  previous_year_units: nullableNumeric.optional(),
  distribution: z.number().int().nullable(),
  previous_year_distribution: z.number().int().nullable().optional(),
  return_rate_pct: nullableNumeric.optional(),
  previous_year_return_rate_pct: nullableNumeric.optional(),
  impact_yoy: numeric,
  impact_recent: numeric,
  score: numeric,
  status,
});

export const monthlyReviewSchema = z.object({
  meta,
  recent_months: z.number().int().min(3).max(12),
  executive: z.array(
    z.object({
      id: z.string(),
      label: z.string(),
      unit: z.enum(['currency', 'percent', 'integer', 'decimal']),
      current: numeric,
      previous_year: nullableNumeric.optional(),
      previous_month: nullableNumeric.optional(),
      recent_average: nullableNumeric.optional(),
      target: nullableNumeric.optional(),
      yoy_delta: nullableNumeric.optional(),
      mom_delta: nullableNumeric.optional(),
      recent_delta: nullableNumeric.optional(),
      target_delta: nullableNumeric.optional(),
      delta_kind: z.enum(['percent', 'percentage-points']),
    }),
  ),
  trend: z.array(
    z.object({
      period: z.string(),
      sales: numeric,
      units: numeric,
      receipts: numeric,
      target: numeric,
      target_pct: nullableNumeric.optional(),
      average_receipt: nullableNumeric.optional(),
      return_rate_pct: nullableNumeric.optional(),
    }),
  ),
  seasonality: z.array(
    z.object({
      year: z.number().int(),
      previous_period: z.string(),
      current_period: z.string(),
      sales_lift_pct: nullableNumeric.optional(),
      units_lift_pct: nullableNumeric.optional(),
      receipts_lift_pct: nullableNumeric.optional(),
      sales_per_store_day_lift_pct: nullableNumeric.optional(),
      store_count: z.number().int(),
      is_current: z.boolean(),
    }),
  ),
  drivers: z.array(
    z.object({
      basis: z.string(),
      baseline_sales: numeric,
      current_sales: numeric,
      sales_difference: numeric,
      receipts_effect: numeric,
      units_per_receipt_effect: numeric,
      value_per_unit_effect: numeric,
    }),
  ),
  companies: z.array(performanceRow),
  managers: z.array(performanceRow),
  stores: z.array(performanceRow),
  categories: z.array(productRow),
  products: z.array(productRow),
  returns: z.array(
    z.object({
      id: z.string(),
      label: z.string(),
      context: z.string(),
      entity_type: z.string(),
      current_value: numeric,
      previous_year_value: nullableNumeric.optional(),
      recent_average_value: nullableNumeric.optional(),
      current_rate_pct: nullableNumeric.optional(),
      previous_year_rate_pct: nullableNumeric.optional(),
      recent_rate_pct: nullableNumeric.optional(),
      yoy_rate_delta_pp: nullableNumeric.optional(),
      recent_rate_delta_pp: nullableNumeric.optional(),
      status,
    }),
  ),
  agents: z.array(performanceRow),
  alerts: z.array(
    z.object({
      id: z.string(),
      severity: z.enum(['info', 'warning', 'critical']),
      title: z.string(),
      description: z.string(),
      entity_label: z.string().nullable().optional(),
    }),
  ),
  methodology: z.array(z.string()),
});

export type MonthlyReview = z.infer<typeof monthlyReviewSchema>;
export type PerformanceReviewRow = z.infer<typeof performanceRow>;
export type ProductReviewRow = z.infer<typeof productRow>;
export type ReviewStatus = z.infer<typeof status>;
