from unihub_insight_api.domain import (
    AnalyticsCatalogResponse,
    Capability,
    ChartKind,
    DimensionDefinition,
    MetricDefinition,
    MetricUnit,
)
from unihub_insight_api.services.monthly_review_contract import (
    MONTHLY_REVIEW_METRICS,
)

KPI_TABLE = (ChartKind.KPI, ChartKind.TABLE)
TREND = (ChartKind.KPI, ChartKind.LINE, ChartKind.AREA, ChartKind.BAR, ChartKind.TABLE)
TREND_MIX = (*TREND[:-1], ChartKind.DONUT, ChartKind.TREEMAP, ChartKind.TABLE)


def metric(
    metric_id: str,
    name: str,
    description: str,
    unit: MetricUnit,
    *,
    aggregation: str = "sum",
    capability: Capability = Capability.ANALYTICS,
    dimensions: tuple[str, ...] = ("firm", "regional", "asm", "store", "agent", "time"),
    grains: tuple[str, ...] = ("day", "month", "year"),
    comparison: str = "previous-period-or-year",
    missing: str = "covered-empty-is-zero",
    shapes: tuple[ChartKind, ...] = TREND,
    suppressible: bool = False,
    source_authority: str = "unihub-retail",
) -> MetricDefinition:
    return MetricDefinition(
        id=metric_id,
        display_name=name,
        description=description,
        unit=unit,
        aggregation=aggregation,
        allowed_dimensions=dimensions,
        allowed_grains=grains,
        comparison_policy=comparison,
        missing_policy=missing,
        required_capability=capability,
        allowed_shapes=shapes,
        suppressible=suppressible,
        source_authority=source_authority,
    )


METRIC_CATALOG: tuple[MetricDefinition, ...] = (
    metric(
        "sales.total",
        "Vânzări",
        "Suma vânzărilor nete de accesorii.",
        MetricUnit.CURRENCY,
        dimensions=("firm", "regional", "asm", "store", "agent", "category", "time"),
        shapes=TREND_MIX,
    ),
    metric(
        "target.progress_pct",
        "Realizare target",
        "Vânzări împărțite la target.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        missing="null-when-target-non-positive",
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HEATMAP, ChartKind.TABLE),
    ),
    metric(
        "forecast.linear",
        "Forecast run-rate",
        "Proiecție liniară explicită până la finalul lunii.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        grains=("month",),
        missing="null-without-cutoff",
        shapes=KPI_TABLE,
    ),
    metric(
        "receipts.total",
        "Bonuri",
        "Numărul canonic de bonuri în scope.",
        MetricUnit.INTEGER,
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "receipts.average_value",
        "Valoare medie bon",
        "Vânzări împărțite la bonuri.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        missing="null-when-no-receipts",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "receipt_2plus_pct",
        "Bonuri cu 2+ accesorii",
        "Ponderea bonurilor cu minimum două accesorii.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        missing="null-when-no-receipts",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "performance.average",
        "Realizare medie",
        "Media ponderată a realizării targetului.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.HEATMAP,
            ChartKind.SCATTER,
            ChartKind.HISTOGRAM,
            ChartKind.BOXPLOT,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "performance.at_target",
        "Entități la target",
        "Numărul entităților cu realizare de minimum 100%.",
        MetricUnit.INTEGER,
        aggregation="count",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "performance.volatility",
        "Volatilitate",
        "Dispersia performanței în fereastra selectată.",
        MetricUnit.PERCENT,
        aggregation="derived",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "performance.daily_productivity",
        "Productivitate / zi-agent",
        "Vânzări împărțite la totalul zilelor-agent acoperite.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        shapes=(ChartKind.KPI, ChartKind.BAR, ChartKind.HISTOGRAM, ChartKind.BOXPLOT, ChartKind.TABLE),
    ),
    metric(
        "campaigns.focus_sales",
        "Vânzări Focus",
        "Vânzările produselor Focus active.",
        MetricUnit.CURRENCY,
        dimensions=("firm", "regional", "asm", "store", "mechanism", "category", "time"),
        shapes=TREND_MIX,
    ),
    metric(
        "campaigns.focus_share",
        "Pondere Focus",
        "Cantitatea Focus din cantitatea totală.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        dimensions=("firm", "regional", "asm", "store", "mechanism", "category", "time"),
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HEATMAP, ChartKind.TABLE),
    ),
    metric(
        "campaigns.active_stores",
        "Magazine active campanie",
        "Magazine cu rezultat pozitiv în campanie.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        dimensions=("firm", "regional", "asm", "store", "mechanism", "time"),
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "campaigns.active_products",
        "Produse Focus active",
        "Numărul de produse distincte cu rezultat Focus în perioada acoperită.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        dimensions=("firm", "regional", "asm", "store", "mechanism", "category", "time"),
        grains=("month",),
        shapes=KPI_TABLE,
        missing="null-without-focus-contract",
    ),
    metric(
        "workforce.headcount",
        "Headcount activ",
        "Agenți activi în perioada acoperită.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        capability=Capability.MANAGEMENT,
        dimensions=("firm", "regional", "asm", "store", "agent", "tenure", "time"),
        shapes=TREND_MIX,
    ),
    metric(
        "workforce.productivity",
        "Productivitate / agent",
        "Vânzări împărțite la headcount.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        capability=Capability.MANAGEMENT,
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.HEATMAP,
            ChartKind.HISTOGRAM,
            ChartKind.BOXPLOT,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "workforce.coverage",
        "Acoperire magazine",
        "Magazine active cu personal în perioada selectată.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-counts",
        capability=Capability.MANAGEMENT,
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "workforce.stability",
        "Stabilitate workforce",
        "Ponderea populației active păstrate conform read-model-ului workforce.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-counts",
        capability=Capability.MANAGEMENT,
        missing="null-without-effective-dated-roster",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "compensation.payroll",
        "Cost salarial",
        "Cost salarial total, inclusiv bonuri conform contractului Retail.",
        MetricUnit.CURRENCY,
        capability=Capability.HR,
        dimensions=("firm", "time"),
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.DONUT,
            ChartKind.TREEMAP,
            ChartKind.HEATMAP,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "compensation.average",
        "Salariu mediu",
        "Media lunară eligibilă conform pragului contractual.",
        MetricUnit.CURRENCY,
        aggregation="average",
        capability=Capability.HR,
        dimensions=("firm", "time"),
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.SCATTER,
            ChartKind.HISTOGRAM,
            ChartKind.BOXPLOT,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "compensation.median",
        "Salariu median",
        "Mediana costului lunar per persoană.",
        MetricUnit.CURRENCY,
        aggregation="median",
        capability=Capability.HR,
        dimensions=("firm", "time"),
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HISTOGRAM, ChartKind.BOXPLOT, ChartKind.TABLE),
    ),
    metric(
        "compensation.sales_ratio",
        "Cost salarial / vânzări",
        "Cost salarial împărțit la vânzări.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        capability=Capability.HR,
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        dimensions=("firm", "time"),
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "finance.revenue",
        "Venit net",
        "Venit P&L din categoriile v1/v11/v2/v3.",
        MetricUnit.CURRENCY,
        capability=Capability.PNL,
        shapes=TREND,
    ),
    metric(
        "finance.ebit",
        "EBIT",
        "Marjă brută minus costuri operaționale și amortizare.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        capability=Capability.PNL,
        dimensions=("firm", "regional", "asm", "store", "category", "time"),
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.WATERFALL, ChartKind.TABLE),
    ),
    metric(
        "finance.ebit_margin",
        "Marjă EBIT",
        "EBIT împărțit la venit.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        capability=Capability.PNL,
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HEATMAP, ChartKind.TABLE),
    ),
    metric(
        "finance.operating_costs",
        "Cost operațional",
        "Costuri P&L din categoriile c3–c6.",
        MetricUnit.CURRENCY,
        capability=Capability.PNL,
        dimensions=("firm", "regional", "asm", "store", "category", "time"),
        shapes=(ChartKind.KPI, ChartKind.BAR, ChartKind.DONUT, ChartKind.TREEMAP, ChartKind.TABLE),
    ),
    metric(
        "planning.forecast",
        "Forecast",
        "Forecast persistat pentru scope și perioadă.",
        MetricUnit.CURRENCY,
        aggregation="sum",
        capability=Capability.MANAGEMENT,
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.AREA, ChartKind.BAR, ChartKind.SCATTER, ChartKind.TABLE),
    ),
    metric(
        "planning.target_gap",
        "Gap față de target",
        "Forecast minus target.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        capability=Capability.MANAGEMENT,
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.TABLE),
    ),
    metric(
        "planning.accuracy",
        "Acuratețe forecast",
        "1 minus eroarea absolută procentuală.",
        MetricUnit.PERCENT,
        aggregation="weighted-derived",
        capability=Capability.MANAGEMENT,
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "planning.actual",
        "Actual disponibil",
        "Actualul Retail reconciliat pentru perioada și scope-ul scenariului.",
        MetricUnit.CURRENCY,
        aggregation="sum",
        capability=Capability.MANAGEMENT,
        missing="null-without-covered-actual",
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.TABLE),
    ),
    *MONTHLY_REVIEW_METRICS,
)


DIMENSION_CATALOG: tuple[DimensionDefinition, ...] = (
    DimensionDefinition(
        id="time",
        display_name="Perioadă",
        description="Perioadă calendaristică cu cutoff și coverage explicite.",
        stable_key="period",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="firm",
        display_name="Companie",
        description="Compania Retail din contractul autoritativ.",
        stable_key="firm_id",
        allowed_grains=("month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="regional",
        display_name="Regional Manager",
        description="Apartenență effective-dated; selecția de magazin domină istoricul.",
        stable_key="regional_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="asm",
        display_name="ASM",
        description="Nivel organizațional păstrat în date, fără selector global dedicat.",
        stable_key="asm_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="store",
        display_name="Magazin",
        description="Cheia operațională stabilă este site_code.",
        stable_key="site_code",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="tenure",
        display_name="Vechime",
        description="Bandă de vechime agregată din read-model-ul workforce.",
        stable_key="tenure_band",
        allowed_grains=("month", "quarter", "year"),
        required_capability=Capability.MANAGEMENT,
        source_authority="reporting_workforce_month_v1",
    ),
    DimensionDefinition(
        id="agent",
        display_name="Agent",
        description="Identitate effective-dated; nu este disponibilă în Compensation.",
        stable_key="agent_entity_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="mechanism",
        display_name="Mecanism campanie",
        description="Promo, Incentive, Concurs, Focus și Folii rămân separate.",
        stable_key="mechanism_id",
        allowed_grains=("month",),
    ),
    DimensionDefinition(
        id="category",
        display_name="Categorie",
        description="Categorie autoritativă din reporting Retail.",
        stable_key="category_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
)


ANALYTICS_CATALOG = AnalyticsCatalogResponse(
    metrics=list(METRIC_CATALOG),
    dimensions=list(DIMENSION_CATALOG),
)
