from unihub_insight_api.domain import (
    AnalyticsCatalogResponse,
    Capability,
    ChartKind,
    DimensionDefinition,
    MetricDefinition,
    MetricUnit,
    ModuleId,
)
from unihub_insight_api.services.monthly_review_contract import (
    MONTHLY_REVIEW_METRICS,
)

KPI_TABLE = (ChartKind.KPI, ChartKind.TABLE)
TREND = (ChartKind.KPI, ChartKind.LINE, ChartKind.AREA, ChartKind.BAR, ChartKind.TABLE)
TREND_MIX = (*TREND[:-1], ChartKind.DONUT, ChartKind.TREEMAP, ChartKind.TABLE)
TEMPORAL_COMPARISONS = ("previous-period", "previous-year", "recent-average")
PORTFOLIO_DIMENSIONS = ("category", "subcategory", "brand", "product")
PORTFOLIO_ITEM_DIMENSIONS = ("brand", "product")
PORTFOLIO_SHAPES = (ChartKind.KPI, ChartKind.BAR, ChartKind.DONUT, ChartKind.TREEMAP, ChartKind.TABLE)
PORTFOLIO_METRIC_IDS = frozenset(
    {
        "sales.portfolio_sales",
        "sales.portfolio_net_quantity",
        "sales.portfolio_return_quantity",
        "sales.portfolio_receipt_incidence",
    }
)

MODULE_PRIMARY_METRIC_IDS: dict[ModuleId, str] = {
    ModuleId.SALES: "sales.total",
    ModuleId.PERFORMANCE: "performance.average",
    ModuleId.CAMPAIGNS: "campaigns.focus_sales",
    ModuleId.WORKFORCE: "workforce.headcount",
    ModuleId.COMPENSATION: "compensation.payroll",
    ModuleId.FINANCE: "finance.revenue",
    ModuleId.PLANNING: "planning.forecast",
}

MODULE_ENTITY_DIMENSIONS: dict[ModuleId, str] = {
    ModuleId.SALES: "store",
    ModuleId.PERFORMANCE: "store",
    ModuleId.CAMPAIGNS: "store",
    ModuleId.WORKFORCE: "agent",
    ModuleId.COMPENSATION: "firm",
    ModuleId.FINANCE: "store",
    ModuleId.PLANNING: "store",
}


def metric_entity_dimension(module: ModuleId, metric_id: str) -> str:
    return "team_leader" if metric_id.startswith("visits.") else MODULE_ENTITY_DIMENSIONS[module]


def metric(
    metric_id: str,
    name: str,
    description: str,
    unit: MetricUnit,
    *,
    aggregation: str = "sum",
    capability: Capability = Capability.ANALYTICS,
    dimensions: tuple[str, ...] = ("firm", "regional", "asm", "store", "agent", "time"),
    grains: tuple[str, ...] = ("day", "month", "year"),
    comparison: str = "previous-period-or-year",
    comparisons: tuple[str, ...] = TEMPORAL_COMPARISONS,
    missing: str = "covered-empty-is-zero",
    shapes: tuple[ChartKind, ...] = TREND,
    suppressible: bool = False,
    source_authority: str = "unihub-retail",
) -> MetricDefinition:
    return MetricDefinition(
        id=metric_id,
        display_name=name,
        description=description,
        unit=unit,
        aggregation=aggregation,
        allowed_dimensions=dimensions,
        allowed_grains=grains,
        comparison_policy=comparison,
        allowed_comparisons=comparisons,
        missing_policy=missing,
        required_capability=capability,
        formula_reference=f"unihub-insight:metric:{metric_id}:v1",
        allowed_shapes=shapes,
        suppressible=suppressible,
        source_authority=source_authority,
    )


def commercial_campaign_metrics(mechanism: str, label: str) -> tuple[MetricDefinition, ...]:
    dimensions = ("firm", "regional", "asm", "store", "mechanism", "category", "time")
    prefix = f"campaigns.{mechanism}"
    return (
        metric(
            f"{prefix}_sales",
            f"Vânzări {label}",
            f"Vânzările nete ale produselor participante în mecanismul {label}.",
            MetricUnit.CURRENCY,
            dimensions=dimensions,
            shapes=TREND_MIX,
            missing="null-without-campaign-publication",
        ),
        metric(
            f"{prefix}_quantity",
            f"Cantitate netă {label}",
            f"Cantitatea netă vândută pentru produsele participante în {label}.",
            MetricUnit.INTEGER,
            dimensions=dimensions,
            shapes=KPI_TABLE,
            missing="null-without-campaign-publication",
        ),
        metric(
            f"{prefix}_{'discount' if mechanism == 'promo' else 'reward'}",
            "Discount Promo" if mechanism == "promo" else "Recompensă Incentive",
            "Valoarea calculată de evaluatorul canonic Retail.",
            MetricUnit.CURRENCY,
            dimensions=dimensions,
            shapes=TREND_MIX,
            missing="null-without-campaign-publication",
        ),
        metric(
            f"{prefix}_active_stores",
            f"Magazine participante {label}",
            "Magazine distincte cu rezultat materializat.",
            MetricUnit.INTEGER,
            aggregation="distinct-count",
            dimensions=dimensions,
            grains=("month",),
            shapes=KPI_TABLE,
            missing="null-without-campaign-publication",
        ),
        metric(
            f"{prefix}_active_products",
            f"Produse participante {label}",
            "Produse distincte active în configurația mecanismului.",
            MetricUnit.INTEGER,
            aggregation="distinct-count",
            dimensions=dimensions,
            grains=("month",),
            shapes=KPI_TABLE,
            missing="null-without-campaign-publication",
        ),
        metric(
            f"{prefix}_{'qualifying_receipts' if mechanism == 'promo' else 'qualified_quantity'}",
            "Bonuri eligibile Promo" if mechanism == "promo" else "Cantitate calificată Incentive",
            "Volumul calificat de evaluatorul canonic Retail.",
            MetricUnit.INTEGER,
            dimensions=dimensions,
            shapes=KPI_TABLE,
            missing="null-without-campaign-publication",
        ),
        metric(
            f"{prefix}_{'discounted_units' if mechanism == 'promo' else 'eligible_quantity'}",
            "Unități cu discount Promo" if mechanism == "promo" else "Cantitate eligibilă Incentive",
            "Volumul eligibil materializat de evaluatorul canonic Retail.",
            MetricUnit.INTEGER,
            dimensions=dimensions,
            shapes=KPI_TABLE,
            missing="null-without-campaign-publication",
        ),
    )


METRIC_CATALOG: tuple[MetricDefinition, ...] = (
    metric(
        "sales.total",
        "Vânzări",
        "Suma vânzărilor nete de accesorii.",
        MetricUnit.CURRENCY,
        dimensions=("firm", "regional", "asm", "store", "agent", "category", "time"),
        comparisons=("target", *TEMPORAL_COMPARISONS),
        shapes=(*TREND_MIX[:-1], ChartKind.CALENDAR, ChartKind.TABLE),
    ),
    metric(
        "sales.portfolio_sales",
        "Vânzări nete portofoliu",
        "Vânzări nete pe categorie, subcategorie, brand real sau produs, din read-model-urile Retail aprobate.",
        MetricUnit.CURRENCY,
        dimensions=PORTFOLIO_DIMENSIONS,
        grains=("month",),
        comparisons=(),
        missing="source-row-missing-remains-missing",
        shapes=PORTFOLIO_SHAPES,
        source_authority="reporting_category_month/reporting_item_month",
    ),
    metric(
        "sales.portfolio_net_quantity",
        "Cantitate netă portofoliu",
        "Cantitate netă pe categorie, subcategorie, brand real sau produs.",
        MetricUnit.INTEGER,
        dimensions=PORTFOLIO_DIMENSIONS,
        grains=("month",),
        comparisons=(),
        missing="source-row-missing-remains-missing",
        shapes=PORTFOLIO_SHAPES,
        source_authority="reporting_category_month/reporting_item_month",
    ),
    metric(
        "sales.portfolio_return_quantity",
        "Cantitate retur semnată",
        "Cantitatea de retur semnată pe brand real sau produs, exclusiv din reporting_item_month.",
        MetricUnit.INTEGER,
        dimensions=PORTFOLIO_ITEM_DIMENSIONS,
        grains=("month",),
        comparisons=(),
        missing="source-row-missing-remains-missing",
        shapes=PORTFOLIO_SHAPES,
        source_authority="reporting_item_month",
    ),
    metric(
        "sales.portfolio_receipt_incidence",
        "Incidențe SKU în bonuri",
        "Suma incidențelor produs-bon pentru SKU; nu reprezintă bonuri distincte.",
        MetricUnit.INTEGER,
        dimensions=("product",),
        grains=("month",),
        comparisons=(),
        missing="source-row-missing-remains-missing",
        shapes=PORTFOLIO_SHAPES,
        source_authority="reporting_item_month",
    ),
    metric(
        "target.progress_pct",
        "Realizare target",
        "Vânzări împărțite la target.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        missing="null-when-target-non-positive",
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HEATMAP, ChartKind.TABLE),
    ),
    metric(
        "forecast.linear",
        "Forecast run-rate",
        "Proiecție liniară explicită până la finalul lunii.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        grains=("month",),
        missing="null-without-cutoff",
        shapes=KPI_TABLE,
    ),
    metric(
        "receipts.total",
        "Bonuri",
        "Numărul canonic de bonuri în scope.",
        MetricUnit.INTEGER,
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "receipts.average_value",
        "Valoare medie bon",
        "Vânzări împărțite la bonuri.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        missing="null-when-no-receipts",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "receipt_2plus_pct",
        "Bonuri cu 2+ accesorii",
        "Ponderea bonurilor cu minimum două accesorii.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        missing="null-when-no-receipts",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "performance.average",
        "Realizare medie",
        "Media ponderată a realizării targetului.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.HEATMAP,
            ChartKind.SCATTER,
            ChartKind.HISTOGRAM,
            ChartKind.BOXPLOT,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "performance.at_target",
        "Entități la target",
        "Numărul entităților cu realizare de minimum 100%.",
        MetricUnit.INTEGER,
        aggregation="count",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "performance.volatility",
        "Volatilitate",
        "Dispersia performanței în fereastra selectată.",
        MetricUnit.PERCENT,
        aggregation="derived",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "performance.daily_productivity",
        "Productivitate / zi-agent",
        "Vânzări împărțite la totalul zilelor-agent acoperite.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        shapes=(ChartKind.KPI, ChartKind.BAR, ChartKind.HISTOGRAM, ChartKind.BOXPLOT, ChartKind.TABLE),
    ),
    metric(
        "campaigns.focus_sales",
        "Vânzări Focus",
        "Vânzările produselor Focus active.",
        MetricUnit.CURRENCY,
        dimensions=("firm", "regional", "asm", "store", "mechanism", "category", "time"),
        shapes=TREND_MIX,
    ),
    metric(
        "campaigns.focus_share",
        "Pondere Focus",
        "Cantitatea Focus din cantitatea totală.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        dimensions=("firm", "regional", "asm", "store", "mechanism", "category", "time"),
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HEATMAP, ChartKind.TABLE),
    ),
    metric(
        "campaigns.active_stores",
        "Magazine active campanie",
        "Magazine cu rezultat pozitiv în campanie.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        dimensions=("firm", "regional", "asm", "store", "mechanism", "time"),
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "campaigns.active_products",
        "Produse Focus active",
        "Numărul de produse distincte cu rezultat Focus în perioada acoperită.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        dimensions=("firm", "regional", "asm", "store", "mechanism", "category", "time"),
        grains=("month",),
        shapes=KPI_TABLE,
        missing="null-without-focus-contract",
    ),
    *commercial_campaign_metrics("promo", "Promo"),
    *commercial_campaign_metrics("incentive", "Incentive"),
    metric(
        "workforce.headcount",
        "Headcount activ",
        "Agenți activi în perioada acoperită.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        capability=Capability.MANAGEMENT,
        dimensions=("firm", "regional", "asm", "store", "agent", "tenure", "time"),
        shapes=TREND_MIX,
    ),
    metric(
        "workforce.productivity",
        "Productivitate / agent",
        "Vânzări împărțite la headcount.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        capability=Capability.MANAGEMENT,
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.HEATMAP,
            ChartKind.HISTOGRAM,
            ChartKind.BOXPLOT,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "workforce.coverage",
        "Acoperire magazine",
        "Magazine active cu personal în perioada selectată.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-counts",
        capability=Capability.MANAGEMENT,
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "workforce.stability",
        "Stabilitate workforce",
        "Ponderea populației active păstrate conform read-model-ului workforce.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-counts",
        capability=Capability.MANAGEMENT,
        missing="null-without-effective-dated-roster",
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "visits.total",
        "Vizite",
        "Numărul vizitelor FieldOps eligibile, atribuite autorului Team Leader din snapshot.",
        MetricUnit.INTEGER,
        aggregation="count",
        dimensions=("firm", "regional", "asm", "store", "team_leader", "time"),
        grains=("month",),
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HEATMAP, ChartKind.TABLE),
        source_authority="reporting_visit_month_v2",
    ),
    metric(
        "visits.distinct_stores",
        "Magazine vizitate",
        "Numărul distinct de magazine cu vizită FieldOps eligibilă în scope.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        dimensions=("firm", "regional", "asm", "store", "team_leader", "time"),
        grains=("month",),
        comparisons=(),
        shapes=KPI_TABLE,
        source_authority="reporting_visit_month_v2",
    ),
    metric(
        "visits.avg_completion",
        "Completion mediu vizite",
        "Media ponderată cu numărul vizitelor a completion-ului FieldOps.",
        MetricUnit.PERCENT,
        aggregation="weighted-average",
        dimensions=("firm", "regional", "asm", "store", "team_leader", "time"),
        grains=("month",),
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.TABLE),
        source_authority="reporting_visit_month_v2",
    ),
    metric(
        "visits.checklist_score",
        "Scor checklist vizite",
        "Media ponderată a celor cinci verificări booleene din vizitele FieldOps.",
        MetricUnit.PERCENT,
        aggregation="weighted-average",
        dimensions=("firm", "regional", "asm", "store", "team_leader", "time"),
        grains=("month",),
        shapes=(ChartKind.KPI, ChartKind.BAR, ChartKind.TABLE),
        source_authority="reporting_visit_month_v2",
    ),
    metric(
        "compensation.payroll",
        "Cost salarial",
        "Cost salarial total, inclusiv bonuri conform contractului Retail.",
        MetricUnit.CURRENCY,
        capability=Capability.HR,
        dimensions=("firm", "time"),
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.DONUT,
            ChartKind.TREEMAP,
            ChartKind.HEATMAP,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "compensation.average",
        "Salariu mediu",
        "Media lunară eligibilă conform pragului contractual.",
        MetricUnit.CURRENCY,
        aggregation="average",
        capability=Capability.HR,
        dimensions=("firm", "time"),
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        shapes=(
            ChartKind.KPI,
            ChartKind.LINE,
            ChartKind.BAR,
            ChartKind.SCATTER,
            ChartKind.HISTOGRAM,
            ChartKind.BOXPLOT,
            ChartKind.TABLE,
        ),
    ),
    metric(
        "compensation.median",
        "Salariu median",
        "Mediana costului lunar per persoană.",
        MetricUnit.CURRENCY,
        aggregation="median",
        capability=Capability.HR,
        dimensions=("firm", "time"),
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HISTOGRAM, ChartKind.BOXPLOT, ChartKind.TABLE),
    ),
    metric(
        "compensation.sales_ratio",
        "Cost salarial / vânzări",
        "Cost salarial împărțit la vânzări.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        capability=Capability.HR,
        suppressible=True,
        source_authority="reporting_compensation_month_v1",
        dimensions=("firm", "time"),
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "finance.revenue",
        "Venit net",
        "Venit P&L din categoriile v1/v11/v2/v3.",
        MetricUnit.CURRENCY,
        capability=Capability.PNL,
        shapes=TREND,
    ),
    metric(
        "finance.ebit",
        "EBIT",
        "Marjă brută minus costuri operaționale și amortizare.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        capability=Capability.PNL,
        dimensions=("firm", "regional", "asm", "store", "category", "time"),
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.WATERFALL, ChartKind.TABLE),
    ),
    metric(
        "finance.ebit_margin",
        "Marjă EBIT",
        "EBIT împărțit la venit.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        capability=Capability.PNL,
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.HEATMAP, ChartKind.TABLE),
    ),
    metric(
        "finance.operating_costs",
        "Cost operațional",
        "Costuri P&L din categoriile c3–c6.",
        MetricUnit.CURRENCY,
        capability=Capability.PNL,
        dimensions=("firm", "regional", "asm", "store", "category", "time"),
        shapes=(ChartKind.KPI, ChartKind.BAR, ChartKind.DONUT, ChartKind.TREEMAP, ChartKind.TABLE),
    ),
    metric(
        "planning.forecast",
        "Forecast",
        "Forecast persistat pentru scope și perioadă.",
        MetricUnit.CURRENCY,
        aggregation="sum",
        capability=Capability.MANAGEMENT,
        comparisons=("target", *TEMPORAL_COMPARISONS),
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.AREA, ChartKind.BAR, ChartKind.SCATTER, ChartKind.TABLE),
    ),
    metric(
        "planning.target_gap",
        "Gap față de target",
        "Forecast minus target.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        capability=Capability.MANAGEMENT,
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.TABLE),
    ),
    metric(
        "planning.accuracy",
        "Acuratețe forecast",
        "1 minus eroarea absolută procentuală.",
        MetricUnit.PERCENT,
        aggregation="weighted-derived",
        capability=Capability.MANAGEMENT,
        grains=("month",),
        shapes=KPI_TABLE,
    ),
    metric(
        "planning.actual",
        "Actual disponibil",
        "Actualul Retail reconciliat pentru perioada și scope-ul scenariului.",
        MetricUnit.CURRENCY,
        aggregation="sum",
        capability=Capability.MANAGEMENT,
        comparisons=("forecast", "target", *TEMPORAL_COMPARISONS),
        missing="null-without-covered-actual",
        shapes=(ChartKind.KPI, ChartKind.LINE, ChartKind.BAR, ChartKind.TABLE),
    ),
    *MONTHLY_REVIEW_METRICS,
)


DIMENSION_CATALOG: tuple[DimensionDefinition, ...] = (
    DimensionDefinition(
        id="time",
        display_name="Perioadă",
        description="Perioadă calendaristică cu cutoff și coverage explicite.",
        stable_key="period",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="firm",
        display_name="Companie",
        description="Compania Retail din contractul autoritativ.",
        stable_key="firm_id",
        allowed_grains=("month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="regional",
        display_name="Regional Manager",
        description="Apartenență effective-dated; selecția de magazin domină istoricul.",
        stable_key="regional_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="asm",
        display_name="ASM",
        description="Nivel organizațional păstrat în date, fără selector global dedicat.",
        stable_key="asm_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="store",
        display_name="Magazin",
        description="Cheia operațională stabilă este site_code.",
        stable_key="site_code",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="tenure",
        display_name="Vechime",
        description="Bandă de vechime agregată din read-model-ul workforce.",
        stable_key="tenure_band",
        allowed_grains=("month", "quarter", "year"),
        required_capability=Capability.MANAGEMENT,
        source_authority="reporting_workforce_month_v1",
    ),
    DimensionDefinition(
        id="agent",
        display_name="Agent",
        description="Identitate effective-dated; nu este disponibilă în Compensation.",
        stable_key="agent_entity_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="team_leader",
        display_name="Team Leader autor vizită",
        description="Autorul păstrat în snapshotul vizitei; nu este ASM-ul curent al magazinului.",
        stable_key="team_leader_id",
        allowed_grains=("month", "quarter", "year"),
        source_authority="reporting_visit_month_v2",
    ),
    DimensionDefinition(
        id="mechanism",
        display_name="Mecanism campanie",
        description="Promo, Incentive, Concurs, Focus și Folii rămân separate.",
        stable_key="mechanism_id",
        allowed_grains=("month",),
    ),
    DimensionDefinition(
        id="category",
        display_name="Categorie",
        description="Categorie autoritativă din reporting Retail.",
        stable_key="category_id",
        allowed_grains=("day", "week", "month", "quarter", "year"),
    ),
    DimensionDefinition(
        id="subcategory",
        display_name="Subcategorie",
        description="Subcategoria Retail, păstrată împreună cu categoria părinte în identificatorul analitic.",
        stable_key="category_subcategory_id",
        allowed_grains=("month",),
        source_authority="reporting_category_month",
    ),
    DimensionDefinition(
        id="brand",
        display_name="Brand",
        description="Brandul real din Monthly Review, atașat fără a modifica măsurile din reporting_item_month.",
        stable_key="brand_normalized",
        allowed_grains=("month",),
        source_authority="insight.monthly_review_item_month",
    ),
    DimensionDefinition(
        id="product",
        display_name="Produs",
        description=(
            "SKU Retail curent, consolidat strict pe item_code; contextul de brand/categorie și eticheta MAX stabilă "
            "sunt semnalate când sursa are variante."
        ),
        stable_key="item_code",
        allowed_grains=("month",),
        source_authority="reporting_item_month",
    ),
)


ANALYTICS_CATALOG = AnalyticsCatalogResponse(
    metrics=list(METRIC_CATALOG),
    dimensions=list(DIMENSION_CATALOG),
)
