from unihub_insight_api.domain import Capability, MetricDefinition, MetricUnit
from unihub_insight_api.services.monthly_review_contract import (
    MONTHLY_REVIEW_METRICS,
)


def metric(
    metric_id: str,
    name: str,
    description: str,
    unit: MetricUnit,
    *,
    aggregation: str = "sum",
    capability: Capability = Capability.ANALYTICS,
    dimensions: tuple[str, ...] = ("firm", "regional", "asm", "store", "agent", "time"),
    grains: tuple[str, ...] = ("day", "month", "year"),
    comparison: str = "previous-period-or-year",
    missing: str = "covered-empty-is-zero",
) -> MetricDefinition:
    return MetricDefinition(
        id=metric_id,
        display_name=name,
        description=description,
        unit=unit,
        aggregation=aggregation,
        allowed_dimensions=dimensions,
        allowed_grains=grains,
        comparison_policy=comparison,
        missing_policy=missing,
        required_capability=capability,
    )


METRIC_CATALOG: tuple[MetricDefinition, ...] = (
    metric("sales.total", "Vânzări", "Suma vânzărilor nete de accesorii.", MetricUnit.CURRENCY),
    metric(
        "target.progress_pct",
        "Realizare target",
        "Vânzări împărțite la target.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        missing="null-when-target-non-positive",
    ),
    metric(
        "forecast.linear",
        "Forecast run-rate",
        "Proiecție liniară explicită până la finalul lunii.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        grains=("month",),
        missing="null-without-cutoff",
    ),
    metric("receipts.total", "Bonuri", "Numărul canonic de bonuri în scope.", MetricUnit.INTEGER),
    metric(
        "receipts.average_value",
        "Valoare medie bon",
        "Vânzări împărțite la bonuri.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        missing="null-when-no-receipts",
    ),
    metric(
        "receipt_2plus_pct",
        "Bonuri cu 2+ accesorii",
        "Ponderea bonurilor cu minimum două accesorii.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        missing="null-when-no-receipts",
    ),
    metric(
        "performance.average",
        "Realizare medie",
        "Media ponderată a realizării targetului.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
    ),
    metric(
        "performance.at_target",
        "Entități la target",
        "Numărul entităților cu realizare de minimum 100%.",
        MetricUnit.INTEGER,
        aggregation="count",
    ),
    metric(
        "performance.volatility",
        "Volatilitate",
        "Dispersia performanței în fereastra selectată.",
        MetricUnit.PERCENT,
        aggregation="derived",
    ),
    metric(
        "campaigns.focus_sales",
        "Vânzări Focus",
        "Vânzările produselor Focus active.",
        MetricUnit.CURRENCY,
    ),
    metric(
        "campaigns.focus_share",
        "Pondere Focus",
        "Cantitatea Focus din cantitatea totală.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
    ),
    metric(
        "campaigns.active_stores",
        "Magazine active campanie",
        "Magazine cu rezultat pozitiv în campanie.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
    ),
    metric(
        "workforce.headcount",
        "Headcount activ",
        "Agenți activi în perioada acoperită.",
        MetricUnit.INTEGER,
        aggregation="distinct-count",
        capability=Capability.MANAGEMENT,
    ),
    metric(
        "workforce.productivity",
        "Productivitate / agent",
        "Vânzări împărțite la headcount.",
        MetricUnit.CURRENCY,
        aggregation="ratio-of-sums",
        capability=Capability.MANAGEMENT,
    ),
    metric(
        "workforce.coverage",
        "Acoperire magazine",
        "Magazine active cu personal în perioada selectată.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-counts",
        capability=Capability.MANAGEMENT,
    ),
    metric(
        "compensation.payroll",
        "Cost salarial",
        "Cost salarial total, inclusiv bonuri conform contractului Retail.",
        MetricUnit.CURRENCY,
        capability=Capability.HR,
    ),
    metric(
        "compensation.average",
        "Salariu mediu",
        "Media lunară eligibilă conform pragului contractual.",
        MetricUnit.CURRENCY,
        aggregation="average",
        capability=Capability.HR,
    ),
    metric(
        "compensation.median",
        "Salariu median",
        "Mediana costului lunar per persoană.",
        MetricUnit.CURRENCY,
        aggregation="median",
        capability=Capability.HR,
    ),
    metric(
        "compensation.sales_ratio",
        "Cost salarial / vânzări",
        "Cost salarial împărțit la vânzări.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        capability=Capability.HR,
    ),
    metric(
        "finance.revenue",
        "Venit net",
        "Venit P&L din categoriile v1/v11/v2/v3.",
        MetricUnit.CURRENCY,
        capability=Capability.PNL,
    ),
    metric(
        "finance.ebit",
        "EBIT",
        "Marjă brută minus costuri operaționale și amortizare.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        capability=Capability.PNL,
    ),
    metric(
        "finance.ebit_margin",
        "Marjă EBIT",
        "EBIT împărțit la venit.",
        MetricUnit.PERCENT,
        aggregation="ratio-of-sums",
        capability=Capability.PNL,
    ),
    metric(
        "finance.operating_costs",
        "Cost operațional",
        "Costuri P&L din categoriile c3–c6.",
        MetricUnit.CURRENCY,
        capability=Capability.PNL,
    ),
    metric(
        "planning.forecast",
        "Forecast",
        "Forecast persistat pentru scope și perioadă.",
        MetricUnit.CURRENCY,
        aggregation="sum",
        capability=Capability.MANAGEMENT,
    ),
    metric(
        "planning.target_gap",
        "Gap față de target",
        "Forecast minus target.",
        MetricUnit.CURRENCY,
        aggregation="derived",
        capability=Capability.MANAGEMENT,
    ),
    metric(
        "planning.accuracy",
        "Acuratețe forecast",
        "1 minus eroarea absolută procentuală.",
        MetricUnit.PERCENT,
        aggregation="weighted-derived",
        capability=Capability.MANAGEMENT,
    ),
    *MONTHLY_REVIEW_METRICS,
)
