import type { DashboardWidgetDefinition } from '../../components/dashboard/types';
import {
  AlertsWidget,
  ContributionWidget,
  ForecastKpiWidget,
  PerformanceWidget,
  ReceiptKpiWidget,
  SalesKpiWidget,
  SalesTrendWidget,
  TargetKpiWidget,
} from './widgets';

export const overviewWidgets: DashboardWidgetDefinition[] = [
  {
    id: 'kpi-sales',
    title: 'Vânzări',
    subtitle: 'Realizat și variație',
    component: SalesKpiWidget,
    x: 0,
    y: 0,
    w: 6,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    id: 'kpi-target',
    title: 'Target',
    subtitle: 'Progres față de obiectiv',
    component: TargetKpiWidget,
    x: 6,
    y: 0,
    w: 6,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    id: 'kpi-forecast',
    title: 'Forecast',
    subtitle: 'Run-rate liniar explicit',
    component: ForecastKpiWidget,
    x: 12,
    y: 0,
    w: 6,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    id: 'kpi-receipts',
    title: 'Bonuri 2+',
    subtitle: 'Calitatea tranzacției',
    component: ReceiptKpiWidget,
    x: 18,
    y: 0,
    w: 6,
    h: 5,
    minW: 4,
    minH: 4,
  },
  {
    id: 'sales-trend',
    title: 'Pace comercială',
    subtitle: 'Realizat, target, forecast și reper',
    component: SalesTrendWidget,
    x: 0,
    y: 5,
    w: 16,
    h: 14,
    minW: 10,
    minH: 9,
  },
  {
    id: 'alerts',
    title: 'Atenție managerială',
    subtitle: 'Abateri explicate, fără scoring opac',
    component: AlertsWidget,
    x: 16,
    y: 5,
    w: 8,
    h: 14,
    minW: 6,
    minH: 8,
  },
  {
    id: 'contribution',
    title: 'Contribuție pe firmă',
    subtitle: 'Pondere în scope-ul curent',
    component: ContributionWidget,
    x: 0,
    y: 19,
    w: 8,
    h: 13,
    minW: 6,
    minH: 9,
  },
  {
    id: 'performance',
    title: 'Magazine prioritare',
    subtitle: 'Sortare și comparație pe entitate',
    component: PerformanceWidget,
    x: 8,
    y: 19,
    w: 16,
    h: 13,
    minW: 10,
    minH: 9,
  },
];
