import type { DashboardWidgetDefinition } from '../../components/dashboard/types';
import type { ModuleAnalytics } from './schemas';
import {
  ModuleAlertsWidget,
  ModuleBreakdownWidget,
  ModuleDistributionWidget,
  ModuleKpiFour,
  ModuleKpiOne,
  ModuleKpiThree,
  ModuleKpiTwo,
  ModuleMatrixWidget,
  ModuleTrendWidget,
} from './widgets';

export function moduleWidgets(data: ModuleAnalytics): DashboardWidgetDefinition[] {
  return [
    {
      id: 'kpi-0',
      title: data.kpis[0]?.label ?? 'KPI principal',
      subtitle: 'Valoare și context',
      component: ModuleKpiOne,
      x: 0,
      y: 0,
      w: 6,
      h: 5,
      minW: 4,
      minH: 4,
    },
    {
      id: 'kpi-1',
      title: data.kpis[1]?.label ?? 'KPI secundar',
      subtitle: 'Valoare și context',
      component: ModuleKpiTwo,
      x: 6,
      y: 0,
      w: 6,
      h: 5,
      minW: 4,
      minH: 4,
    },
    {
      id: 'kpi-2',
      title: data.kpis[2]?.label ?? 'KPI operațional',
      subtitle: 'Valoare și context',
      component: ModuleKpiThree,
      x: 12,
      y: 0,
      w: 6,
      h: 5,
      minW: 4,
      minH: 4,
    },
    {
      id: 'kpi-3',
      title: data.kpis[3]?.label ?? 'KPI complementar',
      subtitle: 'Valoare și context',
      component: ModuleKpiFour,
      x: 18,
      y: 0,
      w: 6,
      h: 5,
      minW: 4,
      minH: 4,
    },
    {
      id: 'trend',
      title: 'Evoluție',
      subtitle: `${data.axes[0]?.label ?? 'Valoare'} pe 12 luni`,
      component: ModuleTrendWidget,
      x: 0,
      y: 5,
      w: 16,
      h: 14,
      minW: 10,
      minH: 9,
    },
    {
      id: 'alerts',
      title: 'Atenție managerială',
      subtitle: 'Reguli explicite și starea datelor',
      component: ModuleAlertsWidget,
      x: 16,
      y: 5,
      w: 8,
      h: 14,
      minW: 6,
      minH: 8,
    },
    {
      id: 'distribution',
      title: 'Distribuție',
      subtitle: 'Contribuție în scope-ul curent',
      component: ModuleDistributionWidget,
      x: 0,
      y: 19,
      w: 8,
      h: 13,
      minW: 6,
      minH: 9,
    },
    {
      id: 'matrix',
      title: 'Matrice temporală',
      subtitle: 'Entitate × perioadă',
      component: ModuleMatrixWidget,
      x: 8,
      y: 19,
      w: 8,
      h: 13,
      minW: 6,
      minH: 9,
    },
    {
      id: 'breakdown',
      title: 'Detaliu entități',
      subtitle: 'Sortare, risc și comparație',
      component: ModuleBreakdownWidget,
      x: 16,
      y: 19,
      w: 8,
      h: 13,
      minW: 8,
      minH: 9,
    },
  ];
}
